apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab-redis
    app.kubernetes.io/instance: gitlab
    chart: redis-0.9.0
    heritage: Helm
    release: gitlab
  name: gitlab-redis
  namespace: default
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: gitlab-redis
