apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab-gitlab-ce
    app.kubernetes.io/instance: gitlab
    chart: gitlab-ce-0.2.3
    heritage: Helm
    release: gitlab
  name: gitlab-gitlab-ce
  namespace: default
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: gitlab-gitlab-ce
  type: LoadBalancer
