apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab-postgresql
    app.kubernetes.io/instance: gitlab
    chart: postgresql-0.8.1
    heritage: Helm
    release: gitlab
  name: gitlab-postgresql
  namespace: default
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: gitlab-postgresql
  type: ClusterIP
