apiVersion: v1
data:
  postgres-password: ++++++++
kind: Secret
metadata:
  labels:
    app: gitlab-postgresql
    app.kubernetes.io/instance: gitlab
    chart: postgresql-0.8.1
    heritage: Helm
    release: gitlab
  name: gitlab-postgresql
  namespace: default
type: Opaque
