apiVersion: v1
data:
  redis-password: ++++++++
kind: Secret
metadata:
  labels:
    app: gitlab-redis
    app.kubernetes.io/instance: gitlab
    chart: redis-0.9.0
    heritage: Helm
    release: gitlab
  name: gitlab-redis
  namespace: default
type: Opaque
